import React, { useState, useEffect } from 'react';
import { Card, FormField, Loader } from '../components';

const HomePage = () => {
  const [loading, setLoading] = useState(false);
  const [posts, setPosts] = useState(null);

  return (
    <section className="max-w-7xl mx-auto">

      <div>
        <h1 className="font-extrabold text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w[500px]">
          Browse through through a collection of imaginative and visually stunning images generated by DALL-E AI.
        </p>
      </div>

      <div className="mt-16">
        <FormField />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
          </>
        )}
      </div>
    </section>
  );
};

export default HomePage;