# Generated by Django 4.1.4 on 2023-02-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50, unique=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Refresh_Token', models.CharField(max_length=150)),
                ('Access_Token', models.CharField(max_length=150)),
                ('Expires_IN', models.DateTimeField()),
                ('Token_Type', models.CharField(max_length=50)),
            ],
        ),
    ]
